AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication API

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 3

Resources:
  AuthApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sign_up/lambda
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SignUpEvent:
          Type: Api
          Properties:
            Path: /signup
            Method: get
            RestApiId:
              Ref: AuthApiGateway

Outputs:
  SignUpApi:
    Description: "API Gateway endpoint URL for dev stage for Sign Up function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  SignUpFunction:
    Description: "Sign Up Lambda Function ARN"
    Value: !GetAtt SignUpFunction.Arn
  SignUpFunctionIamRole:
    Description: "Implicit IAM Role created for Sign Up function"
    Value: !GetAtt SignUpFunctionRole.Arn
