name: Development Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application 
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
      
      - name: Install general dependencies
        run: |
          python -m pip install --upgrade pip  
      
      - name: Check lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check tests and coverage
        run: |
          pip install pytest
          pip install pytest-cov
          export PYTHONPATH=application
          pytest --cache-clear --cov-fail-under=90 --cov=application tests/unit/
      
      - name: Setup sam client
        uses: aws-actions/setup-sam@v1
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Build application
        run: sam build --use-container
      
      - name: Deploy application
        run: |
          sam deploy --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --s3-bucket stb-deployment \
          --stack-name stb-authentication-dev \
          --parameter-overrides Stage=dev \
          --capabilities CAPABILITY_IAM \
          --region ${{ secrets.AWS_REGION }}